### PR TITLE
Multiple ecs containers

### PR DESCRIPTION
**Pull request by sfali**
## Purpose

To allow ECS service discovery to work with multiple containers in ECS task definition.

## References

References #542

## Changes

Introduced optional `akka.discovery.aws-api-ecs.container-name` config to provide container name
if there are multiple containers in ECS task definition to allow ECS service discovery to narrow down
the container running Akka application.

## Background Context

As mentioned in issue #542 with multiple containers in ECS task definition the service discovery failed form cluster, by providing `container-name` service discovery can filter container running Akka application.

### CODE REVIEW

**Comment by milanvdm** [comment]
@chbatey Could someone from the akka-team have a look at this? Without this, AkkaManagement is completely broken on Fargate ECS. We are stuck on the 1.0.0-RC2 release because of it.

**Comment by chbatey** [comment]
@milanvdm sorry for the delay, we were away at team meetings last week. I'll look at this now

**Comment by milanvdm** [comment]
@chbatey No worries, I heard you were on a team event :) I made a PR in the meantime to fix this. Let me know what you think about the approach.

**Comment by chbatey** [comment]
Hi @sfali could you try out https://github.com/akka/akka-management/pull/610 and see if it works for you? If so we can close this PR. Otherwise we're happy to add something like this as it is opt in for a signle discovery mechanism.

**Comment by sfali** [comment]
@chbatey Sure, I am going to take a look at #610 and get back to you

**Comment by johanandren** [comment]
Closing this as it got stale and there was no interaction for a very long while.

**Pull request closed without merging**
