### PR TITLE
Target JDK8 for Java classes

### PR DESCRIPTION
**Pull request by raboof**
Refs #584

### CODE REVIEW

**Comment by olijaun** [comment]
I'm sorry I don't want to push... but this seems like a serious problem. I had to downgrade from 1.0.4 to  1.0.1 of akka-management. I think that JDK 8 is still widely in use. It would be great if this could be merged. Thanks

**Comment by raboof** [comment]
@olijaun thanks for the reminder! Just to check: are you having trouble with `akka.management.cluster.ClusterReadViewAccess` or some other class?

**Comment by olijaun** [comment]
@raboof Yes. Here is an example when I run `curl http://127.0.0.1:8558/cluster/members`

`
[INFO] [11/12/2019 08:35:07.044] [my-cluster-akka.actor.default-dispatcher-21] [akka://my-cluster@127.0.0.1:2550/system/singletonProxymy-singleton-actor-no-dc] Singleton identified at [akka://my-cluster/system/singletonManagermy-singleton-actor/my-singleton-actor]
received message
Uncaught error from thread [my-cluster-akka.actor.default-dispatcher-13]: akka/management/cluster/ClusterReadViewAccess has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[my-cluster]
java.lang.UnsupportedClassVersionError: akka/management/cluster/ClusterReadViewAccess has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
`

**Comment by raboof** [comment]
> So this relies on that we run the publish in travis with java 8?

The other way around: before this PR, `ClusterReadViewAccess.java` was built for whatever JDK you were publishing with. With this PR, it will target JDK8 even when publishing from JDK11.

Travis is already set up to publish with jdk8, but the travis release for 1.0.4 failed due to missing/outdated artifacts (https://travis-ci.org/akka/akka-management/jobs/607515807), so I suspect we released manually with JDK11 causing the problem @olijaun is seeing. This PR would prevent that from happening in the future.

**Comment by chbatey** [comment]
Aha doh, I misread which way around the is was for isJDK8. Gotcha.

**Comment by patriknw** [comment]
sounds important to publish 1.0.5 asap  if 1.04 doesn't run on jdk8

**Pull request merged**
