### PR TITLE
missing port name, it's necessary to pass Kubernetes Ready probe

### PR DESCRIPTION
**Pull request by franciscolopezsancho**

### CODE REVIEW

**Comment by johanandren** [comment]
Hmm, but this test was passing already before, so the port name is not really necessary?

**Comment by franciscolopezsancho** [comment]
OK. I did a test in local and didn't work for me (on my laptop : ) until I added it so I thought. But if you have tests that pass with this I'll close it, np. I didn't know about those.

**Comment by franciscolopezsancho** [comment]
BTW when I said testing in local is not with a Spec but actually deploying in a Kubernetes Cluster.

**Comment by johanandren** [comment]
Hmm, ok, well, the test passes with it as well, but would be good to understand why it would fail in one case but not in the integration tests.

**Comment by franciscolopezsancho** [comment]
I'm looking into it. When I find what's the difference I'll open it again.

**Pull request closed without merging**
