### PR TITLE
Add Minikube to Travis CI 

### PR DESCRIPTION
**Pull request by sebastianharko**
Add minikube to Travis CI so that integration testing can be done for this project.

Followed instructions outlined in this blog post: https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube ... 

Cheers!

### CODE REVIEW

**Comment by ktoso** [comment]
I guess tests should then issue normal command line commands for k8s or how?
Thanks for the code!

**Comment by sebastianharko** [comment]
@ktoso the tests can use Kubernetes Java API ! And, yes, I do plan to add a minimal test as well so don't merge the PR just yet

**Comment by ktoso** [comment]
How would we test things for DCOS or other things?
I'm very worried about more and more functionality being contributed without any test coverage, e.g.: https://github.com/akka/akka-management/pull/110

How would we test that?

If we need cash we can arrange that, could you help out figuring how what our options are?

**Comment by sebastianharko** [comment]
@ktoso I don't know too much about DCOS but I know enough about Kubernetes and AWS. Here's how I would "integration" / "end to end" test: I would leverage the **demo** projects. So, after the normal build finishes on Travis CI, we run an integration test (written in Scala) that basically programatically mimics the steps in the demo tutorials and checks if a cluster is well formed ... How does this sound ?
Let me know your thoughts.

**Comment by ktoso** [comment]
Yes this sounds very good, should we merge this now or you want to add things here right away?

**Comment by sebastianharko** [comment]
@ktoso feel free to merge

**Pull request merged**
