### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by ikr**
References #xxxx

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ikr,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]
LGTM, but however ridiculous it may seem for such a small change we'd need a CLA sign off :)

**Comment by ikr** [comment]
I think I did sign the CLA. Got this in mail:


Thank you for signing the Lightbend CLA.

If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA.

We are looking forward to your contributions!

The Lightbend Team
email: [info@lightbend.com](mailto:%20info@lightbend.com)
[lightbend.com](https://lightbend.com/)

**Review by patriknw — APPROVED** [review]
thanks

**Pull request merged**
