### PR TITLE
Drop 2.11 support

### PR DESCRIPTION
**Pull request by chbatey**
This will require a 1.1 release. 

Refs #618

### CODE REVIEW

**Comment by patriknw** [comment]
I don't mind dropping 2.11 but I don't see that we need a 1.1 release for that. It will increase our maintenance burden to keep two branches alive.

Could we drop 2.11 for upcoming 1.0.x releases without starting to use 2.12 only features? Waiting some for feedback to see if there are any important complaints?

**Comment by chbatey** [comment]
Yep let’s do that

**Comment by patriknw** [comment]
Given what we heard from the Play team we need to reconsider.

What was the main reason for dropping 2.11? Is that worth the alternative to maintain two branches?

**Comment by chbatey** [comment]
It was to reduce overhead, having just had a build fail due to 2.11, so if we need 2 branches then that defeats the purpose :)

**Pull request closed without merging**
