### PR TITLE
marathon-api add docker-support

### PR DESCRIPTION
**Pull request by ygree**
@longshorej I added Docker support. When a docker container selected, a port name declaration placed in different location of an application description: `apps/contatiner/docker/portMappings`

### CODE REVIEW

**Comment by ygree** [comment]
@ktoso @longshorej I will add a doc and an example when I will be able to get back to this. Thanks!

**Comment by ktoso** [comment]
See linked ticket about adding testing infra

**Comment by ktoso** [comment]
I mean this one: https://github.com/akka/akka-management/pull/110

Is there any way we can write real tests for this?
I'm very worried about continious adding of features without any integration tests, esp since I don't have the expertise to know if those things work or not even ;)

**Comment by ygree** [comment]
@ktoso @longshorej I added an example along with the change to support Docker containers. I tested example on DC/OS.

**Comment by ktoso** [comment]
Thanks, I'll merge this

**Pull request merged**
