### PR TITLE
Adding client project and implementation

### PR DESCRIPTION
**Pull request by roarking**
This PR adds a client module with Akka HTTP bindings to interface with the HTTP management service programmatically using a Scala API.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @roarking,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Please first open issues when wanting to propose such bigger changes, mostly as outlined in: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#akka-contributing-guidelines

I don't think this is something the project should include. See my PR in https://github.com/akka/akka-management/pull/69 where we expose the Uri's to the endpoints and people can consume them however they want:

```
object ClusterBootstrapRequests {

  import akka.http.scaladsl.client.RequestBuilding._

  def bootstrapSeedNodes(baseUri: Uri): HttpRequest =
    Get(baseUri + "/bootstrap/seed-nodes")

}
```

**Comment by roarking** [comment]
Sounds good to me. Are these changes irrelevant to this repo then? If so, I can close this PR.

**Comment by ktoso** [comment]
Yeah I think so sadly, sorry to waste your time -- please first open a ticket next time implementing things :-)

**Comment by ktoso** [comment]
Looking forward to your support in other issues in this project I hope? :)

**Comment by roarking** [comment]
Not at all - this is something we originally wrote to use internally, so no time wasted. :) Thanks for the quick reply.

**Pull request closed without merging**
