### PR TITLE
backport joining to Akka 2.4

### PR DESCRIPTION
**Pull request by patriknw**
Don't merge until we have tested in master. I expect to have to redo this if there are too many changes in master.

The first commit is the cherry pick of the initial PR commit.
The second commit is the needed changes for Akka 2.4, especially `Timers`.

It's the second commit that should be reviewed here.

### CODE REVIEW

**Comment by patriknw** [comment]
Also note that I created the release-2.4 branch which includes everything from master except the multi-dc fixes.

**Comment by patriknw** [comment]
@longshorej @fsat you can `publishLocal` from this `wip-joining-2.4-patriknw` branch if you want to try with Akka 2.4.

**Comment by fsat** [comment]
@patriknw - thanks for backporting this for us!

**Comment by longshorej** [comment]
Thanks @patriknw - this is working nicely, [Chirper](https://github.com/lagom/lagom-java-chirper-example) is working with our tooling and the new bootstrapping.

I'd still like to talk about if we could make a subproject that only has `provided` dependencies on `akka-cluster` and no dependency on `ru.smslv.akka-dns` -- I'd be happy to provide a PR -- but we can deal with that once the inflight work is complete.

**Pull request merged**
