### PR TITLE
Replace `bootstrap-joining-demo` to `bootstrap-demo` 

### PR DESCRIPTION
**Pull request by jupeter**
I started from find bad link in documentation. 
Found all places where "bootstrap-joining-demo" is set and fix names to "bootstrap-demo".

If you need any updates, please let me know.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jupeter,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
Thanks! This might have some overlap with #341 but that doesn't have to be a problem. After #348 is merged Travis checks should be functional again and we can validate PR's as usual again ;)

**Comment by jupeter** [comment]
Hi @raboof . 
Thank you for a response. 
After merge #341 I will rebase my branch if any conflict appear.

**Comment by raboof** [comment]
@jupeter the other PR's are now merged, so after a rebase this PR should be good to go as well now!

**Comment by jupeter** [comment]
Done

**Pull request merged**
