### PR TITLE
drop scala 2.11

### PR DESCRIPTION
**Pull request by ignasi35**

### CODE REVIEW

**Comment by chbatey** [comment]
Are we doing this in a patch release or are we going to bump this to 1.1 at least?

**Comment by johanandren** [comment]
+0.1 for bumping to 1.1

**Comment by ignasi35** [comment]
I was aiming at 1.0.10 because scala 2.11 has been EOS for a while now but I don't mind retargetting to 1.1.0.

IIUC, the only reason why we should keep 2.11 around so long would be supporting Lagom 1.5 which will be EOS in few weeks.

**Comment by patriknw** [comment]
Let's also drop support for Akka 2.5.x and make it 1.1.0.

**Comment by patriknw** [comment]
could someone create the `release-1.0.x` branch before we merge those changes so that we know the branch point.

**Comment by ignasi35** [comment]
> could someone create the `release-1.0.x` branch before we merge those changes so that we know the branch point.

I'll block the merge of this PR and postpone the creation of the `release-1.0.x` branch until we've released `1.0.10` to reduce backports.

**Comment by ignasi35** [comment]
created https://github.com/akka/akka-management/tree/release-1.0.x

**Comment by ignasi35** [comment]
> could someone create the `release-1.0.x` branch before we merge those changes so that we know the branch point.

Hehehe. Turns out we already had a `release1.0` (no `.x` suffix) in `master`. created on the `1.0.9` tag. See https://github.com/akka/akka-management/pull/784#issuecomment-716356790

I'll drop the branch `release-1.0` which has not commits and keep `release-1.0.x` which I created from the  `1.0.10` tag. :-)

**Comment by ignasi35** [comment]
> Hehehe. Turns out we already had a `release1.0` (no `.x` suffix) in `master`. created on the `1.0.9` tag. See [#784 (comment)](https://github.com/akka/akka-management/pull/784#issuecomment-716356790)
> 
> I'll drop the branch `release-1.0` which has not commits and keep `release-1.0.x` which I created from the `1.0.10` tag. :-)

Scratch that. The naming convention in `akka/akka` favors keeping `release-1.0` over `release-1.0.x` so I'll drop the later.

**Review by johanandren — APPROVED** [review]

**Pull request merged**
