### PR TITLE
chore: akka-http to 2.7.0-M1, akka to 2.10.0-M1, align with changes from upstream

### PR DESCRIPTION
**Pull request by sebastian-alfers**

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, I don't think the k8 test failure is related, it's probably flaky or something else broken with it in the env

**Comment by johanandren** [comment]
I just merged another PR to main let's wait with merging this and see if the k8 test fails there as well

**Comment by sebastian-alfers** [comment]
It succeeded on `main`?!

**Comment by sebastian-alfers** [comment]
It is this one: https://github.com/akka/akka-management/blob/main/samples/akka-sample-cluster-kubernetes-scala/build.sbt#L8

Should I revert the akka version on that build to make it pass, release an m1 of akka-management, and the bump the integration-tests?

**Comment by johanandren** [comment]
Let's give that a shot.

**Comment by sebastian-alfers** [comment]
That did it.  Once we merge this, I make the M1 and will bump.

**Review by johanandren — APPROVED** [review]

**Pull request merged**
