### PR TITLE
Load multiple ca certificates from file for kubernetes api discovery

### PR DESCRIPTION
**Pull request by khujo**
This PR will load multiple CA certificates from a file provided to the kubernetes api discovery. This is necessary because in case of OpenShift, the cluster will have multiple CAs and the ca.crt file will thus contain multiple certificates.

There are two things I would like to bring up for discussion.

1. Every certificate needs a unique key when added to the trust store. Before this PR the key was the atomic string "cacert". To create a unique key I now append a random string of 6 chars. I don't know if this is the best solution. 
2. The PemManagersProvider is copied from Akka-HTTP. So this PR will introduce a difference to the source in Akka-HTTP. Maybe this issue should also be fixed in Akka-HTTP.

References #947

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @cpqngbot,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by octonato — COMMENTED** [review]
Thanks @khujo 

The build will fail because of bin-compat issues. Please, check the MiMa output. You will need to add MiMa exclusions.

**Comment by khujo** [comment]
Hi @octonato,
the MiMa output did not report any issues. However, it failed because mimaPreviousArtifact was not set for akka-management-pki after the 1.1.1 release. I pushed a new commit to set this value.

**Review by octonato — APPROVED** [review]
Thanks @khujo. 

You are right, we won't need MiMa because the `PemManagersProvider` object is private. All fine in that case.

**Comment by jvdgeest** [comment]
I'm just curious why this PR has not been merged yet? I would really appreciate this fix.

**Comment by octonato** [comment]
@jvdgeest, no special reason. We lost if from sight. I will merge it.

**Comment by jvdgeest** [comment]
Thanks a lot @octonato!

**Pull request merged**
