### PR TITLE
Security support for Akka Discovery Marathon API #429

### PR DESCRIPTION
**Pull request by zromi18**
* New configuration properties for Marathon API based discovery
* Service Account based authentication with private/public key encryption
* User based authentication with username and password

### CODE REVIEW

**Comment by raboof** [comment]
@ignacioPL @ygree can you review this one?

**Comment by raboof** [comment]
Sorry for leaving this hanging for so long! I'm afraid I don't feel up-to-speed enough with Marathon to be able to review this properly.

I wonder if we should move `discovery-marathon-api` to its own repository and make it (more) explicitly community-maintained, giving more contributors merge rights?

**Comment by chbatey** [comment]
We're currently looking for help maintaining the discovery API. Once we have some volunteers we can start revewing/merging marathon related PRs. Sorry for the delay @zromi18

**Comment by johanandren** [comment]
Since we got no volunteers stepping up the last three years, I'll close this PR for now.

**Pull request closed without merging**
