### PR TITLE
Update to Akka 2.6

### PR DESCRIPTION
**Pull request by raboof**
This means we require akka 2.6 instead of 2.5 going forward.

Refs #783

### CODE REVIEW

**Comment by patriknw** [comment]
This means that we would create a 2.5 maintenance branch and backport critical bug fixes. I think it can be about time to do that now. Akka Management has been rather stable lately so shouldn't be too much overhead of backporting. Also in line with that we want to phase out Akka 2.5.

**Comment by SethTisue** [comment]
Arnout's PR already did the trick in the community build: https://github.com/scala/community-build/pull/1252

**Comment by ennru** [comment]
Needs a rebase.

**Comment by patriknw** [comment]
I have created branch `release-1.0` so we can continue development on `master` for Akka 2.6 only and upcoming 1.1.0 release.

`release-1.0` was branched from the `v1.0.9` commit afeaa4b3.
We will only backport critical security and bug fixes to `release-1.0` from now on.

**Comment by SethTisue** [comment]
(nbd, but: is there anything blocking this from being merged?)

**Comment by ignasi35** [comment]
I'll rebase this...

**Comment by ignasi35** [comment]
note: "drop scala 2.11" is not on its own RP #856

**Comment by ignasi35** [comment]
Meh, the target branch is gone. I can't retarget this PR to `akka:master`. I'll recreate the PR separately.

**Pull request closed without merging**
