### PR TITLE
Cross-build to Scala 2.13

### PR DESCRIPTION
**Pull request by dwijnand**
Needs a 2.13.0-RC1 release of Akka-HTTP.

### CODE REVIEW

**Comment by dwijnand** [comment]
This is broken because there's no akka-http for Scala 2.13.0-RC1.  With Scala 2.13.0-RC2 now out, as soon as there's an akka-http build for it, we can update this PR and land it.

This PR is relevant because akka-management is a dependency of Lagom.

**Comment by SethTisue** [comment]
@dwijnand you branch-deleter, you! :-)

I was using this branch in the Scala 2.13 community build. (I could/should have said so here.)

What should I use instead? Does somebody else have a similar branch? Or should I just use master?

**Comment by SethTisue** [comment]
I went on a search-and-rescue mission and was able to locate the commit in a workspace directory on the community build Jenkins worker, and I pushed it to GitHub here: https://github.com/scalacommunitybuild/akka-management/commits/community-build-2.13

that solves the immediate problem, but I am still curious what's next here

**Comment by dwijnand** [comment]
`git fetch origin pull/539/head:213`

> what's next here

There's another RC at #557.

**Comment by dwijnand** [comment]
I ran out the door and realised I'd forgotten to say: sorry deleting the branch broke the CB.  I wouldn't have had I known (I tend to push for those to be in the community build org instead).

**Comment by SethTisue** [comment]
no worries, it’s just an admittedly somewhat dodgy thing I temporarily do during release pushes

**Comment by raboof** [comment]
1.0.1 for RC2 is now on Maven Central, and #557 and #562 are ready to update master to RC3

**Pull request closed without merging**
