### PR TITLE
bumping to upgrade scala-xml to 2.1.0

### PR DESCRIPTION
**Pull request by franciscolopezsancho**
References https://github.com/lightbend/akka-meta/issues/278

### CODE REVIEW

**Comment by franciscolopezsancho** [comment]
This way we only have scala-xml 2.1.0
```
sbt:akka-management-root> whatDependsOn org.scala-lang.modules scala-xml_2.12
[info] org.scala-lang.modules:scala-xml_2.12:2.1.0 [S]
[info]   +-org.scalatest:scalatest-core_2.12:3.2.12 [S]
[info]     +-org.scalatest:scalatest-diagrams_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-featurespec_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-flatspec_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-freespec_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-funspec_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-funsuite_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-matchers-core_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest-mustmatchers_2.12:3.2.12 [S]
[info]     | | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     | |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     | |
[info]     | +-org.scalatest:scalatest-shouldmatchers_2.12:3.2.12 [S]
[info]     | | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     | |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     | |
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-propspec_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-refspec_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest-wordspec_2.12:3.2.12 [S]
[info]     | +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]     |   +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
[info]     |
[info]     +-org.scalatest:scalatest_2.12:3.2.12 [S]
[info]       +-com.lightbend.akka.management:akka-lease-kubernetes-int-test_2.12:1.2.0-14-7ac61825-20230112-1213-SNAPSHOT
```

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Please update https://github.com/akka/akka-management/blob/main/.scala-steward.conf#L6 as well.

**Review by johanandren — APPROVED** [review]
LGTM!

**Pull request merged**
