### PR TITLE
Ignore pending pods

### PR DESCRIPTION
**Pull request by DennisVDB**
References #920

Fixes the issue where pending pods (no `containerStatuses` field return by the k8s api) would fail the retrieval of the pod list. The json decoder always expected the `containerStatuses` field in the response.

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM

We will need some mima exclusions because of change in PodStatus (see https://github.com/akka/akka-management/pull/928/checks?check_run_id=3180624670#step:6:555)

Alternative would be to return `Seq.empty` if the field is not available. That would avoid the mima exclusion, but I guess it's more idiomatic to use `Option` for missing json fields.

**Comment by octonato** [comment]
@DennisVDB, for the mima exclusion, you will need to add a file under src/main/mima-filters with the previous version in the name. See https://github.com/akka/akka-management/blob/master/lease-kubernetes/src/main/mima-filters/1.0.9.backwards.excludes as example.

**Review by raboof — APPROVED** [review]
sorry

**Comment by thjaeckle** [comment]
@raboof will this be part of a 1.1.x bugfix release?

**Pull request merged**
