### PR TITLE
Upgrade to Akka 2.5.21

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by renatocaval** [comment]
Can this be added to upcoming v1.0.0?

**Comment by patriknw** [comment]
Yes, we can start out with latest, but otherwise a library like this shoild be conservative to updating to latest, because that forces all dependencies to be at that at a minimum.

**Comment by dwijnand** [comment]
Everyone should be using latest.

**Comment by patriknw** [comment]
Yes, but by own will and not enforced by someone else :)

**Comment by dwijnand** [comment]
"Enforced" implies there's a resistance.  What resistance is there to be upgraded to latest Akka?  (And by latest, I mean latest binary-compatible, patch version).

**Comment by dwijnand** [comment]
Oh, wait!!  I keep making the same mistake and thinking that a bump for 2.5.20 to 2.5.21 is just bug fixes... that's not true for Akka, it could also be new buggy enhancements or features. Wow, I can't see anything but SemVer anymore.

**Comment by renatocaval** [comment]
> "Enforced" implies there's a resistance. What resistance is there to be upgraded to latest Akka?

It doesn't mean that there is an inherent resistance to upgrade to latest Akka. I understand that rather as: a user may have a reason for not updating. We never know what are their reasons.

**Comment by raboof** [comment]
Build failed due to #481

**Comment by raboof** [comment]
Build failed due to #481

**Comment by chbatey** [comment]
Needs a rebase

**Pull request merged**
