### PR TITLE
docs: Repository tag had a sneaky space

### PR DESCRIPTION
**Pull request by johanandren**

### CODE REVIEW

**Review by patriknw — COMMENTED** [review]
hope this is not something that has been copy-pasted inte many more places?

**Comment by johanandren** [comment]
I'll double check

**Comment by johanandren** [comment]
Actually I was wrong about this being the cause, it's the same everywhere and works.

The reason it was broken is likely that when the published manually backport publish of the docs was made the paradox bump including the directive was missed. I'll republish.

**Comment by johanandren** [comment]
Republished docs with right paradox and everything is fine. Reverted this PR since it wasn't the cause.

**Pull request merged**
